#!/usr/bin/python

import argparse

# Empyre imports
from lib.common import empyre

if __name__ == '__main__':

    parser = argparse.ArgumentParser()
    parser.add_argument('--debug', action='store_true', help='Debug mode for output.')
    parser.add_argument('-debug', action='store_true', help='Debug mode for output.')
    args = parser.parse_args()

    main = empyre.MainMenu(args=args)
    main.cmdloop()
